### ISSUE TITLE
DPL-359 - As developers we need to share information about the technologies we are using with ToL to ensure they have enough information to interact with the messaging sytem (S=M)

### ISSUE THREAD

**Issue by stevieing** [sanger/lab-share-lib#14]
**Description**
As developers we need to share information about the technologies we are using with ToL to ensure they have enough information to interact with the messaging sytem

**Who the primary contacts are for this work**
Eduardo
Stuart
Andrew

**Acceptance criteria**

- [x] Meeting with TOL
- [x] Share documentation with message format and required credentials to connect to the services (Rabbitmq and Redpanda).
- [x] Show process to them  about how to get the latest schema from Redpanda
- [x] Explain the process of versioning and schemas in redpanda so they validate with the right version
- [x] Advise about how to encode an Avro message using the schema (recommend libraries or identify a library they can use depending on the language/framework they want to use)
- [x] Advise about required data (redpanda subject and version number) that have to be in the headers of the message
- [x] Show how to publish a message to the exchange with persistence (explain why persistence is important)
- [x] Show them how to consume feedback messages from the feedback queue

**Dependencies**

- sanger/tol_consumer#2 

**Knowledge or Stake holders**
Other people that may have specific knowledge about this work or have a stake in how it is implemented. e.g. John Smith is an expert on x

**Additional context or information**
Any other useful context or information that may be useful.

**Comment by emrojo** [comment]
To UAT, please someone could check if this works in their machines?:

```bash
git clone https://github.com/sanger/lab-share-lib.git
cd lab-share-lib
git checkout dpl359_add_more_documentation
cd examples
./dependencies/up.sh
pipenv shell
pipenv install
python ./example1/publisher_example.py
python ./example1/consumer_example.py
```
